[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Use our custom plugin first
[[plugins]]
  package = "./netlify-plugin-nextjs-edge"

# Then use the official Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle all routes for client-side navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
